### ISSUE TITLE
Splice Accepts integers parameters in parse but does not act as expected

### ISSUE THREAD

**Issue by Mee42** [neverRare/stringed-old#2]
The following input:
```
"hi"[1:2]
```
returns
```
= hi
```
Which was unexpected :)

**Comment by Mee42** [comment]
looks like your lexer just drops integers all together
```
1
error: invalid expression, it can't be empty
"hi" 1 "hi"
error: unexpected string
"hi" 1 + "hi"          
= hihi
```

**Comment by neverRare** [comment]
well, theres no integer, only string, that could be rewritten as `"hi"["1":"2"]` which is kind of stupid of course

**Comment by Mee42** [comment]
While that makes sense, you should think about having the lexer error when encountering an unknown token - say a 1 - instead of discarding

**Comment by neverRare** [comment]
initially, I thought of that would be ignored the same way as brain fuck, it would be a comment, but then I realized stringed isn't purely symbolic. that should be an error. alrighty then, thanks for the suggestion.
